TraineeTracker/TraineeTracker.MVC/Controllers/TestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TraineeTracker.MVC.Contracts;
using TraineeTracker.MVC.Models;

namespace TraineeTracker.MVC.Controllers
{
    [Route("[controller]/[action]")]
    [Authorize(Roles = "Trainee")]
    public class TestsController : Controller
    {
        private readonly ITestService _testService;

        public TestsController(ITestService testService)
        {
            _testService = testService;
        }

        [Route("/Tests")]
        public async Task<IActionResult> Index(string searchString, string sortOrder, string[] filters)
        {
            ViewData["Sort"] = sortOrder;
            ViewData["Search"] = searchString;
            ViewData["Filters"] = filters;

            var model = await _testService.GetCategories(searchString, sortOrder, filters);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTest(CategoryVM category)
        {
            if (ModelState.IsValid)
            {
                var response = await _testService.CreateTest(category.Id);
                if (response.Success)
                {
                    TempData["TestId"] = response.Data;
                    return RedirectToAction(nameof(Category), new { category = category.Name, q = 1 });
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }

            return RedirectToAction(nameof(Index));
        }

        [Route("/Tests/{category}")]
        public async Task<IActionResult> Category(string category, int? q)
        {
            if(TempData["TestId"] == null) return BadRequest();

            var model = await _testService.GetQuestionWithCount(category, q ?? 1);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAnswer(CreateAnswerVM answerVM, string category, int q, int total, int count)
        {
            int testId = await _testService.GetLatestTraineeTestId();
            TempData["TestId"] = testId;

            if (ModelState.IsValid)
            {
                var response = await _testService.CreateAnswer(answerVM, testId, q-1, count);
                if (!response.Success)
                    ModelState.AddModelError("", response.ValidationErrors);
            }

            if(q <= total)
                return RedirectToAction(nameof(Category), new { category, q });

            return RedirectToAction(nameof(Result));
        }

        public async Task<IActionResult> Result()
        {
            if (TempData["TestId"] == null) return BadRequest();

            var result = await _testService.GetResult();
            return View(result);
        }

        public async Task<IActionResult> Review(int testId, string category, int? q)
        {
            var model = await _testService.GetReviewVM(testId, q ?? 1, category);
            return View(model);
        }

        public async Task<IActionResult> Reviews(string searchString, string sortOrder, string[] filters, int? page)
        {
            ViewData["Sort"] = sortOrder;
            ViewData["Search"] = searchString;
            ViewData["Filters"] = filters;

            var model = await _testService.GetReviewListVM(searchString, sortOrder, filters, page);
            return View(model);
        }
    }
}

TraineeTracker/TraineeTracker.MVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TraineeTracker.MVC.Contracts;
using TraineeTracker.MVC.Models;

namespace TraineeTracker.MVC.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        private readonly ITrainerService _trainerService;
        private readonly ITraineeService _traineeService;

        public UsersController(IUserService userService, ITrainerService trainerService, 
            ITraineeService traineeService)
        {
            _userService = userService;
            _trainerService = trainerService;
            _traineeService = traineeService;
        }

        public async Task<ActionResult> Index(string searchString, string sortOrder, string[] filter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            ViewData["Filter"] = filter;

            var model = await _userService.GetUserAdminList(searchString, sortOrder, filter, pageNumber);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTrainer(RegisterTrainerVM trainer)
        {
            if (ModelState.IsValid)
            {
                var response = await _trainerService.CreateTrainer(trainer);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTrainee(RegisterTraineeVM trainer)
        {
            if (ModelState.IsValid)
            {
                var response = await _traineeService.CreateTrainee(trainer);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

TraineeTracker/TraineeTracker.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trainee Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TraineeTracker.MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <h3 class="text-white m-0">Trainee Tracker</h3>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse ms-3 d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Users" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Tracker" asp-action="Trainees">Trackers</a>
                            </li>
                        }
                        @if (User.IsInRole("Trainee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Tracker" asp-action="Index">Trackers</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Tests
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-controller="Tests" asp-action="Index">Tests</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Tests" asp-action="Reviews">Reviews</a>
                                    </li>
                                    @*<li>
                                        <a class="dropdown-item" asp-controller="Tests" asp-action="Analytics">Analytics</a>
                                    </li>*@
                                </ul>
                            </li>
                        }
                        @if (User.IsInRole("Trainer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Tracker" asp-action="Trainer">Trackers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Trainee" asp-action="Index">Trainees</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; @DateTime.Now.Year - Trainee Tracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>