TraineeTracker/TraineeTracker.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TraineeTracker.MVC.Contracts;
using TraineeTracker.MVC.Models;

namespace TraineeTracker.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeService _homeService;

        public HomeController(ILogger<HomeController> logger, IHomeService homeService)
        {
            _logger = logger;
            _homeService = homeService;
        }

        public async Task<IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account");

            if(User.IsInRole("Administrator"))
            {
                var model = await _homeService.GetAdminHome();
                return View("Admin_Home", model);
            }

            if (User.IsInRole("Trainer"))
            {
                var model = await _homeService.GetTrainerHome();
                return View("TrainerHome", model);
            }

            if (User.IsInRole("Trainee"))
            {
                var model = await _homeService.GetTraineeHome();
                return View("TraineeHome", model);
            }

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TraineeTracker/TraineeTracker.MVC/Controllers/TrackerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TraineeTracker.MVC.Contracts;
using TraineeTracker.MVC.Models;

namespace TraineeTracker.MVC.Controllers
{
    [Authorize]
    public class TrackerController : Controller
    {
        private readonly ITrackerService _trackerService;

        public TrackerController(ITrackerService trackerService)
        {
            _trackerService = trackerService;
        }

        [Authorize(Roles = "Trainee")]
        public async Task<IActionResult> Index(DateTime? date)
        {
            var model = await _trackerService.GetTracker(date);
            return View(model);
        }

        [Authorize(Roles = "Trainee")]
        public async Task<IActionResult> Trackers(string searchString, string sortOrder,
            string[] filter, int? pageNumber)
        {
            ViewData["Sort"] = sortOrder;
            ViewData["Search"] = searchString;
            ViewData["Filter"] = filter;

            var model = await _trackerService
                .GetTraineeTrackers(searchString, sortOrder, filter, pageNumber);
            return View(model);
        }

        [Authorize(Roles = "Trainer")]
        public async Task<IActionResult> Trainer(string searchString, string sortOrder,
            string[] filter, int? pageNumber)
        {
            ViewData["Sort"] = sortOrder;
            ViewData["Search"] = searchString;
            ViewData["Filter"] = filter;

            var model = await _trackerService
                .GetTrackersByTrainer(searchString, sortOrder, filter, pageNumber);
            return View(model);
        }

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Trainees(string searchString, string sortOrder,
            string[] filter, int? pageNumber)
        {
            ViewData["Sort"] = sortOrder;
            ViewData["Search"] = searchString;
            ViewData["Filter"] = filter;

            var model = await _trackerService
                .GetTrackers(searchString, sortOrder, filter, pageNumber);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainee")]
        public async Task<IActionResult> CreateTracker(CreateTrackerVM trackerVM)
        {
            if (ModelState.IsValid)
            {
                var response = await _trackerService.CreateTracker(trackerVM);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

TraineeTracker/TraineeTracker.MVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TraineeTracker.MVC.Contracts;
using TraineeTracker.MVC.Models;

namespace TraineeTracker.MVC.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        private readonly ITrainerService _trainerService;
        private readonly ITraineeService _traineeService;

        public UsersController(IUserService userService, ITrainerService trainerService, 
            ITraineeService traineeService)
        {
            _userService = userService;
            _trainerService = trainerService;
            _traineeService = traineeService;
        }

        public async Task<ActionResult> Index(string searchString, string sortOrder, string[] filter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            ViewData["Filter"] = filter;

            var model = await _userService.GetUserAdminList(searchString, sortOrder, filter, pageNumber);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTrainer(RegisterTrainerVM trainer)
        {
            if (ModelState.IsValid)
            {
                var response = await _trainerService.CreateTrainer(trainer);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateTrainee(RegisterTraineeVM trainer)
        {
            if (ModelState.IsValid)
            {
                var response = await _traineeService.CreateTrainee(trainer);
                if (response.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", response.ValidationErrors);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

TraineeTracker/TraineeTracker.MVC/Views/Home/Admin_Home.cshtml
@model AdminHomeVM

@{
    ViewData["Title"] = "Dashboard";
}

<section class="container mt-4">
    <div class="row">
        <div class="d-flex p-0 justify-content-center gap-5">
            <div class="col-lg-3 col-md-4">
                <div class="rounded shadow h-50">
                    <div class="d-flex justify-content-between p-3">
                        <div>
                            <h5 class="text-secondary text-opacity-75 mt-2">Users</h5>
                            <h2 class="text-secondary">@Model.UserCount</h2>
                        </div>
                        <div class="bg-primary px-2 py-1 rounded opacity-75 h-50">
                        <span><i class="bi bi-people-fill text-info" style="font-size: 1.5em"></i></span>
                        </div>
                    </div>
                    <div class="p-2 px-3">
                        <a asp-controller="Users" asp-action="Index" class="text-secondary nav-link">More Info <i class="bi bi-arrow-right-circle-fill"></i></a>
                    </div>
                </div>
                <div class="rounded shadow mt-4">
                    <div class="d-flex justify-content-between p-3">
                        <div>
                            <h5 class="text-secondary text-opacity-75 mt-2">Trainers</h5>
                            <h2 class="text-secondary">@Model.TrainerCount</h2>
                        </div>
                        <div class="bg-danger px-2 py-1 rounded opacity-75 h-50">
                            <span><i class="bi bi-person-fill text-light" style="font-size: 1.5em"></i></span>
                        </div>
                    </div>                
                </div>
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="rounded shadow h-50">
                    <div class="d-flex justify-content-between p-3">
                        <div>
                            <h5 class="text-secondary text-opacity-75 mt-2">Trackers</h5>
                            <h2 class="text-secondary">@Model.TrackerCount</h2>
                        </div>
                        <div class="bg-success px-2 py-1 rounded opacity-75 h-50">
                            <span><i class="bi bi-file-text-fill text-green" style="font-size: 1.5em"></i></span>
                        </div>
                    </div>
                    <div class="p-2 px-3">
                        <a asp-controller="Tracker" asp-action="Trainees" class="text-secondary nav-link">More Info <i class="bi bi-arrow-right-circle-fill"></i></a>
                    </div>
                </div>
                <div class="rounded shadow mt-4">
                    <div class="d-flex justify-content-between p-3">
                        <div>
                            <h5 class="text-secondary text-opacity-75 mt-2">Trainees</h5>
                            <h2 class="text-secondary">@Model.TraineeCount</h2>
                        </div>
                        <div class="bg-warning px-2 py-1 rounded opacity-75 h-50">
                            <span><i class="bi bi-person-fill text-light" style="font-size: 1.5em"></i></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-5 rounded p-3 shadow">
                <div id="chart3"></div>
            </div>
        </div>
    </div>
    <br/>
    
    <div class="row mt-3">
        <div class="col-5 rounded p-3 shadow me-auto">
            <div id="chart1"></div>
        </div>
        <div class="col-5 rounded p-3 shadow ms-auto">
            <div id="chart2"></div>
        </div>
    </div>
</section>

@section Scripts {
    <script>
        var options1 = {
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Consultant Skill Level'
            },
            series: [@Model.ConsultantSkillCount[0],
                    @Model.ConsultantSkillCount[1],
                    @Model.ConsultantSkillCount[2],
                    @Model.ConsultantSkillCount[3]],
            labels: ['Skilled', 'Partially Skilled', 'Low Skilled', 'Unskilled']
        }

        var chart1 = new ApexCharts(document.querySelector("#chart1"), options1);

        chart1.render();

        var options2 = {
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Technical Skill Level'
            },
            series: [@Model.TechnicalSkillCount[0],
                    @Model.TechnicalSkillCount[1],
                    @Model.TechnicalSkillCount[2],
                    @Model.TechnicalSkillCount[3]],
            labels: ['Skilled', 'Partially Skilled', 'Low Skilled', 'Unskilled']
        }

        var chart2 = new ApexCharts(document.querySelector("#chart2"), options2);

        chart2.render();

        var options3 = {
            chart: {
                type: 'bar'
            },
            title: {
                text: 'Number of Trackers Per Month'
            },
            series: [{
                data: [
                    @Model.TrackersPerMonth[0],
                    @Model.TrackersPerMonth[1],
                    @Model.TrackersPerMonth[2],
                    @Model.TrackersPerMonth[3],
                    @Model.TrackersPerMonth[4],
                    @Model.TrackersPerMonth[5],
                    @Model.TrackersPerMonth[6],
                    @Model.TrackersPerMonth[7],
                    @Model.TrackersPerMonth[8],
                    @Model.TrackersPerMonth[9],
                    @Model.TrackersPerMonth[10],
                    @Model.TrackersPerMonth[11],
                ]
            }],
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        }

        var chart3 = new ApexCharts(document.querySelector("#chart3"), options3);

        chart3.render();
    </script>
}

TraineeTracker/TraineeTracker.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TraineeTracker/TraineeTracker.MVC/Views/Home/TraineeHome.cshtml
@model TraineeHomeVM

@{
    ViewData["Title"] = "Dashboard";
}

<section class="container mt-4">
    <div class="row gap-3">
        <div class="col-4 p-0">
            <div class="card shadow" style="height: 400px">
                <div class="card-header bg-danger">
                    <h4 class="text-light">Alerts</h4>
                </div>
                <div class="card-body overflow-auto">
                    @if (!Model.HasThisWeeksTracker)
                    {
                        <p class="card-text text-danger" role="alert">
                            Don't forget to complete this weeks <a class="link-info" asp-controller="Tracker" asp-action="Index">tracker</a>.
                        </p>
                    }
                </div>
            </div>
        </div>
        <div class="col-7 rounded p-3 shadow">
            <div id="chart3"></div>
        </div>
        <div class="col-5 rounded p-3 shadow" style="width: 46%">
            <div id="chart1"></div>
        </div>
        <div class="col-5 rounded p-3 shadow" style="width: 46%">
            <div id="chart2"></div>
        </div>
    </div>
</section>

@section Scripts {
    <script>
        var options1 = {
            chart: {
                type: 'pie',
                height: 350
            },
            title: {
                text: 'Consultant Skill Level'
            },
            series: [@Model.ConsultantSkillCount[0],
        @Model.ConsultantSkillCount[1],
        @Model.ConsultantSkillCount[2],
        @Model.ConsultantSkillCount[3]],
            labels: ['Skilled', 'Partially Skilled', 'Low Skilled', 'Unskilled']
        }

        var chart1 = new ApexCharts(document.querySelector("#chart1"), options1);

        chart1.render();

        var options2 = {
            chart: {
                type: 'pie',
                height: 350
            },
            title: {
                text: 'Technical Skill Level'
            },
            series: [@Model.TechnicalSkillCount[0],
        @Model.TechnicalSkillCount[1],
        @Model.TechnicalSkillCount[2],
        @Model.TechnicalSkillCount[3]],
            labels: ['Skilled', 'Partially Skilled', 'Low Skilled', 'Unskilled']
        }

        var chart2 = new ApexCharts(document.querySelector("#chart2"), options2);

        chart2.render();

        //$.ajax({
        //    type: "GET",           
        //    url: url,
        //    beforeSend: function (xhr) {
        //        xhr.setRequestHeader('Authorization', 'Bearer @Model.Token')
        //    },
        //    success: renderChart,
        //    error: function (request, status, error) {
        //        console.log(error)
        //    }
        //})

        const trackers = JSON.parse('@Model.Trackers'.replaceAll('&quot;','"'))
        renderChart(trackers)

        function convertData(skill) {
            switch (skill) {
                case 'Unskilled': return 1
                    break;
                case 'Low Skilled': return 2
                    break;
                case 'Partially Skilled': return 3
                    break;
                case 'Skilled': return 4
                    break;
            }
        }

        function renderChart(data) {
            const conSkill = data.map(t => t = [new Date(t.StartDate).getTime(), convertData(t.ConsultantSkill)]);
            const techSkill = data.map(t => t = [new Date(t.StartDate).getTime(), convertData(t.TechnicalSkill)]);
            var options3 = {
                chart: {
                    type: 'line',
                    height: 350,
                },
                title: {
                    text: 'Skill Progression Over Time'
                },
                series: [{
                    name: 'Consultant Skill',
                    data: conSkill
                }, {
                    name: 'Technical Skill',
                    data: techSkill
                }],
                xaxis: {
                    type: 'datetime'
                },
                yaxis: {
                    min: "Unskilled",
                    max: "Skilled",                   
                    labels: {
                        minWidth: 60,
                        formatter: function (value) {
                            switch (value) {
                                case 1: return 'Unskilled'
                                    break;
                                case 2: return 'Low Skilled'
                                    break;
                                case 3: return 'Partially Skilled'
                                    break;
                                case 4: return 'Skilled'
                                    break;
                              
                            }
                        }
                    },
                },
            }

            var chart3 = new ApexCharts(document.querySelector("#chart3"), options3);

            chart3.render();

        }
    </script>
}

TraineeTracker/TraineeTracker.MVC/Views/Home/TrainerHome.cshtml
@model TrainerHomeVM

@{
    ViewData["Title"] = "Dashboard";
}

<section class="container mt-4">
    <div class="row gap-3">
        <div class="col-6">
            <div class="row h-100 gap-3">
                <div class="col-5 p-0">
                    <div class="rounded shadow">
                        <div class="d-flex justify-content-between p-3">
                            <div>
                                <h5 class="text-secondary text-opacity-75 mt-2">Trainees</h5>
                                <h2 class="text-secondary">@Model.TraineeCount</h2>
                            </div>
                            <div class="bg-primary px-2 py-1 rounded opacity-75 h-50">
                                <span><i class="bi bi-people-fill text-info" style="font-size: 1.5em"></i></span>
                            </div>
                        </div>
                        <div class="p-2 px-3">
                            <a asp-controller="Trainee" asp-action="Index" class="text-secondary nav-link">More Info <i class="bi bi-arrow-right-circle-fill"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-5 p-0 ms-auto">
                    <div class="rounded shadow">
                        <div class="d-flex justify-content-between p-3">
                            <div>
                                <h5 class="text-secondary text-opacity-75 mt-2">Trackers</h5>
                                <h2 class="text-secondary">@Model.TrackerCount</h2>
                            </div>
                            <div class="bg-success px-2 py-1 rounded opacity-75 h-50">
                                <span><i class="bi bi-file-text-fill text-green" style="font-size: 1.5em"></i></span>
                            </div>
                        </div>
                        <div class="p-2 px-3">
                            <a asp-controller="Tracker" asp-action="Trainer" class="text-secondary nav-link">More Info <i class="bi bi-arrow-right-circle-fill"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-12 rounded p-3 shadow">
                    <div id="chart3"></div>
                </div>
            </div>
        </div>
        <div class="col-5">
            <div class="row gap-3">
                <div class="col-12 rounded p-3 shadow">
                    <div id="chart2"></div>
                </div>
                <div class="col-12 rounded p-3 shadow">
                    <div id="chart1"></div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts {
    <script>
        var options1 = {
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Consultant Skill Level'
            },
            series: [@Model.ConsultantSkillCount[0],
        @Model.ConsultantSkillCount[1],
        @Model.ConsultantSkillCount[2],
        @Model.ConsultantSkillCount[3]],
            labels: ['Skilled', 'Partially Skilled', 'Low Skilled', 'Unskilled']
        }

        var chart1 = new ApexCharts(document.querySelector("#chart1"), options1);

        chart1.render();

        var options2 = {
            chart: {
                type: 'pie'
            },
            title: {
                text: 'Technical Skill Level'
            },
            series: [@Model.TechnicalSkillCount[0],
        @Model.TechnicalSkillCount[1],
        @Model.TechnicalSkillCount[2],
        @Model.TechnicalSkillCount[3]],
            labels: ['Skilled', 'Partially Skilled', 'Low Skilled', 'Unskilled']
        }

        var chart2 = new ApexCharts(document.querySelector("#chart2"), options2);

        chart2.render();

        var options3 = {
            chart: {
                type: 'bar'
            },
            title: {
                text: 'Number of Trackers Per Month'
            },
            series: [{
                data: [
        @Model.TrackersPerMonth[0],
        @Model.TrackersPerMonth[1],
        @Model.TrackersPerMonth[2],
        @Model.TrackersPerMonth[3],
        @Model.TrackersPerMonth[4],
        @Model.TrackersPerMonth[5],
        @Model.TrackersPerMonth[6],
        @Model.TrackersPerMonth[7],
        @Model.TrackersPerMonth[8],
        @Model.TrackersPerMonth[9],
        @Model.TrackersPerMonth[10],
        @Model.TrackersPerMonth[11],
                ]
            }],
            labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        }

        var chart3 = new ApexCharts(document.querySelector("#chart3"), options3);

        chart3.render();
    </script>
}